/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Backend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Frontend": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
